2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_setup.py:_flush():68] Configure stats pid to 8680
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_setup.py:_flush():68] Loading settings from /opt/ml/.config/wandb/settings
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_setup.py:_flush():68] Loading settings from /opt/ml/code/level1_imageclassification_cv-level1-cv-15/wandb/settings
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'train.py'}
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_init.py:_log_setup():476] Logging user logs to /opt/ml/code/level1_imageclassification_cv-level1-cv-15/wandb/run-20221102_074603-2nm38q8c/logs/debug.log
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_init.py:_log_setup():477] Logging internal logs to /opt/ml/code/level1_imageclassification_cv-level1-cv-15/wandb/run-20221102_074603-2nm38q8c/logs/debug-internal.log
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_init.py:init():516] calling init triggers
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_init.py:init():569] starting backend
2022-11-02 07:46:03,676 INFO    MainThread:8680 [wandb_init.py:init():573] setting up manager
2022-11-02 07:46:03,678 INFO    MainThread:8680 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-02 07:46:03,680 INFO    MainThread:8680 [wandb_init.py:init():580] backend started and connected
2022-11-02 07:46:03,682 INFO    MainThread:8680 [wandb_init.py:init():658] updated telemetry
2022-11-02 07:46:03,701 INFO    MainThread:8680 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-02 07:46:03,858 WARNING MainThread:8680 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-11-02 07:46:08,085 WARNING MsgRouterThr:8680 [router.py:message_loop():77] message_loop has been closed
